# Generated by Django 5.2.4 on 2025-08-04 12:46

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(default=builtins.print, on_delete=django.db.models.deletion.CASCADE, to='carapp.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carapp.model'),
            preserve_default=False,
        ),
    ]
