# Generated by Django 5.2.4 on 2025-08-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_remove_car_brand_remove_car_model_brand_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='carapp.car'),
            preserve_default=False,
        ),
    ]
