# Generated by Django 5.2.4 on 2025-08-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_model_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_feedback', to='carapp.car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='carapp.car'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='carapp.car'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car_image',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
