# Generated by Django 5.2.4 on 2025-08-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_feedback_car_alter_auction_car_alter_carimage_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
